Using api
samwel-mongare/bookstore pull request #3
Opened 2022-01-21 21:50 UTC by Mosams

### The branch usning_API has the following features to be merged into the development branch:

- Refactored the Add book functionality to post to the bookstore API.
- Fetched the books through the 'Get' method from the API.
- Refactored the delete book functionality in order for it to delete a book from the bookstore API.

2022-01-21 22:25 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Sam, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
Git flow is followed. :heavy_check_mark:
PR has a title and summary. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-21 22:25 UTC, SajjadAhmad14 commented on src/redux/books/api.js
> +  await axios.post('https://us-central1-bookstore-api-e63c8.cloudfunctions.net/bookstoreApi/apps/QiDluot0X8BBAUYhtRYg/books', newBook);
Please make sure `add book` and `remove book` features should persist all changes in the server. The user is unable to see added books after the page is refreshed.

2022-01-21 22:25 UTC, SajjadAhmad14 commented on src/redux/books/api.js
> +export const getBooks = () => async (dispatch) => {
Please make server requests in the componentDidMount lifecycle method or with react hooks.

2022-01-21 22:25 UTC, SajjadAhmad14 commented on package.json
>    "version": "0.1.0",
The screenshot and live link are broken in the README. Please add the active content or remove the option so it will look more professional.

2022-01-22 03:12 UTC, julie-ify approved these changes
## Hi @Mosams, 

# Highlights
- Good job implementing the required changes from the previous reviewer ✔️  

# Status: Approved ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![Approved emoji](https://user-images.githubusercontent.com/81468675/147213535-ab80a883-5bf8-4284-b9ee-d90332328671.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 03:12 UTC, julie-ify commented on src/components/BooksUI/Booklist.js
> +  }, [dispatch]);
- [ ] Good use of `useEffect` hook to make request to the server 👍 💯 
- [ ] The user is now able to see added books after the page is refreshed. 👍

2022-01-22 03:31 UTC, merged